/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.clsClientes;
import modelo.clsTarjetas;

/**
 *
 * @author Est_Nautico
 */
public class frmTarjetas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmClientes
     */
    public frmTarjetas() {
        initComponents();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnElminar.setEnabled(false);
        this.cargarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDatosCliente = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblNumeroCuenta = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        txtMontoLimite = new javax.swing.JTextField();
        lblMontoLimite = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        panOperaciones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnElminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panOperaciones1 = new javax.swing.JPanel();
        scrScrollPlato1 = new javax.swing.JScrollPane();
        tblTarjetas = new javax.swing.JTable();

        setClosable(true);
        setTitle("Catalogo de Clientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N

        panDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario Tarjetas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        panDatosCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCedula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCedula.setText("Cedula Cliente");
        panDatosCliente.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        txtCedula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panDatosCliente.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 51, 114, -1));

        lblNumeroCuenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNumeroCuenta.setText("Número de Cuenta");
        panDatosCliente.add(lblNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtNumeroCuenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panDatosCliente.add(txtNumeroCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 114, -1));

        txtMontoLimite.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panDatosCliente.add(txtMontoLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, -1));

        lblMontoLimite.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMontoLimite.setText("Monto Limite");
        panDatosCliente.add(lblMontoLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblSaldo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSaldo.setText("Saldo");
        panDatosCliente.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtSaldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSaldo.setText("0");
        panDatosCliente.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 114, -1));

        panOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/save.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/edit.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnElminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/delete.png"))); // NOI18N
        btnElminar.setFocusCycleRoot(true);
        btnElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btnCancelar.setFocusCycleRoot(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOperacionesLayout = new javax.swing.GroupLayout(panOperaciones);
        panOperaciones.setLayout(panOperacionesLayout);
        panOperacionesLayout.setHorizontalGroup(
            panOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnElminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        panOperacionesLayout.setVerticalGroup(
            panOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnElminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panOperaciones1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tarjetas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblTarjetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Numero", "Limite", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTarjetasMouseClicked(evt);
            }
        });
        scrScrollPlato1.setViewportView(tblTarjetas);

        javax.swing.GroupLayout panOperaciones1Layout = new javax.swing.GroupLayout(panOperaciones1);
        panOperaciones1.setLayout(panOperaciones1Layout);
        panOperaciones1Layout.setHorizontalGroup(
            panOperaciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOperaciones1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrScrollPlato1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        panOperaciones1Layout.setVerticalGroup(
            panOperaciones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOperaciones1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrScrollPlato1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panOperaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panOperaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTabla() {
        clsTarjetas c = new clsTarjetas();
        ArrayList<Object> tarjetas = c.getRegistros();
        DefaultTableModel model = (DefaultTableModel) tblTarjetas.getModel();
        //borrar filas
        model.setRowCount(0);

        for (Object tarjeta : tarjetas) {
            clsTarjetas cl = (clsTarjetas) tarjeta;
            //generar la fila
            model.addRow(new Object[]{cl.getCedula(),
                cl.getNumeroCuenta(),
                cl.getMontoLimite(),
                cl.getSaldo()});
        }
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        clsTarjetas c = new clsTarjetas(txtCedula.getText(),
                Integer.parseInt(txtNumeroCuenta.getText()),
                Double.parseDouble(txtMontoLimite.getText()),
                Double.parseDouble(txtSaldo.getText()));
        if (c.guardar() == 1) {
            JOptionPane.showMessageDialog(null, "Cliente Guardado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            this.cargarTabla();
            CancelarBtn();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido guardar la información", "Error", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "Estas seguro modificar este registro", "Mensaje", JOptionPane.YES_NO_OPTION);

        if (opc == 0) {

            clsTarjetas c = new clsTarjetas(txtCedula.getText(),
                    Integer.parseInt(txtNumeroCuenta.getText()),
                    Double.parseDouble(txtMontoLimite.getText()),
                    Double.parseDouble(txtSaldo.getText()));

            if (c.modificar() == 1) {
                JOptionPane.showMessageDialog(null, "Cliente modificado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                this.cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha podido modificar la información", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            CancelarBtn();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "Estas seguro eliminar este registro", "Mensaje", JOptionPane.YES_NO_OPTION);

        if (opc == 0) {
            clsTarjetas c = new clsTarjetas(txtCedula.getText(),
                    Integer.parseInt(txtNumeroCuenta.getText()),
                    Double.parseDouble(txtMontoLimite.getText()),
                    Double.parseDouble(txtSaldo.getText()));

            if (c.eliminar() == 1) {
                JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                this.cargarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "No se ha podido eliminar la información", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            CancelarBtn();
        }
    }//GEN-LAST:event_btnElminarActionPerformed

    private void tblTarjetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTarjetasMouseClicked
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnElminar.setEnabled(true);

        clsTarjetas c = new clsTarjetas();
        c = (clsTarjetas) c.getRegistro(tblTarjetas.getSelectedRow());
        txtCedula.setText(c.getCedula());
        txtNumeroCuenta.setText(String.valueOf(c.getNumeroCuenta()));
        txtMontoLimite.setText(String.valueOf(c.getMontoLimite()));
        txtSaldo.setText(String.valueOf(c.getSaldo()));

    }//GEN-LAST:event_tblTarjetasMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnElminar.setEnabled(false);
        limpiarCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void limpiarCampos() {
        txtCedula.setText("");
        txtNumeroCuenta.setText("");
        txtMontoLimite.setText("");
        txtSaldo.setText("");
    }

    private void CancelarBtn() {
        limpiarCampos();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnElminar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnElminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblMontoLimite;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JPanel panDatosCliente;
    private javax.swing.JPanel panOperaciones;
    private javax.swing.JPanel panOperaciones1;
    private javax.swing.JScrollPane scrScrollPlato1;
    private javax.swing.JTable tblTarjetas;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtMontoLimite;
    private javax.swing.JTextField txtNumeroCuenta;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables

}
