package vista;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.clsCentroFormacion;
import modelo.clsModulos;
import modelo.clsPrograma;

public class frmProgramas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmProgramas
     */
    public frmProgramas() {
        initComponents();
        cmbHorario.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnElminar.setEnabled(false);
        this.cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFormulario = new javax.swing.JPanel();
        lblReferencia = new javax.swing.JLabel();
        cmbReferencia = new javax.swing.JComboBox<>();
        lblHorario = new javax.swing.JLabel();
        cmbHorario = new javax.swing.JComboBox<>();
        lblSector = new javax.swing.JLabel();
        txtSector = new javax.swing.JTextField();
        lblCodigoPrograma = new javax.swing.JLabel();
        txtCodigoPrograma = new javax.swing.JTextField();
        lblGrupo = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        lblAnno = new javax.swing.JLabel();
        txtAnno = new javax.swing.JTextField();
        cmbModulos = new javax.swing.JComboBox<>();
        lblModulo = new javax.swing.JLabel();
        panOperaciones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnElminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panTabla = new javax.swing.JPanel();
        scrScroll = new javax.swing.JScrollPane();
        tblProgramas = new javax.swing.JTable();
        panModulos = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Programas");

        panFormulario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario Programas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblReferencia.setText("Referencia:");

        lblHorario.setText("Horario");

        lblSector.setText("Sector");

        lblCodigoPrograma.setText("Codigo");

        lblGrupo.setText("Grupo");

        lblAnno.setText("Año");

        lblModulo.setText("Modulos");

        javax.swing.GroupLayout panFormularioLayout = new javax.swing.GroupLayout(panFormulario);
        panFormulario.setLayout(panFormularioLayout);
        panFormularioLayout.setHorizontalGroup(
            panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioLayout.createSequentialGroup()
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFormularioLayout.createSequentialGroup()
                        .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReferencia))
                        .addGap(18, 18, 18)
                        .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHorario)))
                    .addComponent(cmbModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModulo)
                    .addGroup(panFormularioLayout.createSequentialGroup()
                        .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSector)
                            .addComponent(txtSector)
                            .addComponent(lblGrupo)
                            .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodigoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnno)
                            .addComponent(txtCodigoPrograma)
                            .addComponent(txtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panFormularioLayout.setVerticalGroup(
            panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panFormularioLayout.createSequentialGroup()
                        .addComponent(lblReferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panFormularioLayout.createSequentialGroup()
                                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panFormularioLayout.createSequentialGroup()
                                        .addComponent(lblSector)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panFormularioLayout.createSequentialGroup()
                                        .addComponent(lblCodigoPrograma)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panFormularioLayout.createSequentialGroup()
                                .addComponent(lblAnno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panFormularioLayout.createSequentialGroup()
                        .addComponent(lblHorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/save.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/edit.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnElminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/delete.png"))); // NOI18N
        btnElminar.setFocusCycleRoot(true);
        btnElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btnCancelar.setFocusCycleRoot(true);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panOperacionesLayout = new javax.swing.GroupLayout(panOperaciones);
        panOperaciones.setLayout(panOperacionesLayout);
        panOperacionesLayout.setHorizontalGroup(
            panOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panOperacionesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panOperacionesLayout.setVerticalGroup(
            panOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnElminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Programas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        tblProgramas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Referencia", "Modulos", "Sector", "Grupo", "Año", "Centro Formacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProgramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProgramasMouseClicked(evt);
            }
        });
        scrScroll.setViewportView(tblProgramas);
        if (tblProgramas.getColumnModel().getColumnCount() > 0) {
            tblProgramas.getColumnModel().getColumn(0).setResizable(false);
            tblProgramas.getColumnModel().getColumn(1).setResizable(false);
            tblProgramas.getColumnModel().getColumn(2).setResizable(false);
            tblProgramas.getColumnModel().getColumn(3).setResizable(false);
            tblProgramas.getColumnModel().getColumn(4).setResizable(false);
            tblProgramas.getColumnModel().getColumn(5).setResizable(false);
            tblProgramas.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout panTablaLayout = new javax.swing.GroupLayout(panTabla);
        panTabla.setLayout(panTablaLayout);
        panTablaLayout.setHorizontalGroup(
            panTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                .addContainerGap())
        );
        panTablaLayout.setVerticalGroup(
            panTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout panModulosLayout = new javax.swing.GroupLayout(panModulos);
        panModulos.setLayout(panModulosLayout);
        panModulosLayout.setHorizontalGroup(
            panModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        panModulosLayout.setVerticalGroup(
            panModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(panModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(panOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (this.validar())
        {            
            clsPrograma m = new clsPrograma(txtCodigoPrograma.getText(), txtSector.getText(),
                    txtGrupo.getText(), Integer.parseInt(txtAnno.getText()));
            
            clsCentroFormacion centroFormacion = new clsCentroFormacion();
            ArrayList<Object> centros = centroFormacion.getRegistros();
            String selectedItem = (String) cmbReferencia.getSelectedItem();

            clsModulos Mod1 = new clsModulos();
            ArrayList<Object> modulos = Mod1.getRegistros();
            String selectModulo = (String) cmbModulos.getSelectedItem();

            for (Object centro : centros)
            {
                clsCentroFormacion tempCentro = (clsCentroFormacion) centro;
                                
                if(selectedItem.equals(tempCentro.getCodigo())){
                  System.out.println(selectedItem);
                  m.setReferencia(selectedItem);
                  m.setCentroFormacion(tempCentro);
                }
            }

            //rellenar la lista de modulos disponibles    
            for (Object modulo : modulos)
            {
                clsModulos ModuloTemp = (clsModulos) modulo;
                
                clsModulos m1 = (clsModulos) modulo;
                if(selectModulo.equals(ModuloTemp.getNombre())){
                    System.out.println(ModuloTemp.getNombre());
                    m.setModulos(m1);
                }
                
            }
             
            if (m.guardar() == 1)
            {
                JOptionPane.showMessageDialog(null, "Programa Guardado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                this.cargarTabla();
                CancelarBtn();
            } else
            {
                JOptionPane.showMessageDialog(null, "No se ha podido guardar la información", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (this.validar())
        {
            int opc = JOptionPane.showConfirmDialog(null, "Estas seguro modificar este registro", "Mensaje", JOptionPane.YES_NO_OPTION);

            if (opc == 0)
            {

                clsPrograma m = new clsPrograma(txtSector.getText(), txtCodigoPrograma.getText(),
                    txtGrupo.getText(), Integer.parseInt(txtAnno.getText()));
                if (m.modificar() == 1)
                {
                    JOptionPane.showMessageDialog(null, "Programa modificado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    this.cargarTabla();
                } else
                {
                    JOptionPane.showMessageDialog(null, "No se ha podido modificar la información", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
                CancelarBtn();
            }
        } 
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "Estas seguro eliminar este registro", "Mensaje", JOptionPane.YES_NO_OPTION);

        if (opc == 0)
        {
           
            
            clsPrograma m = new clsPrograma( txtCodigoPrograma.getText(),txtSector.getText(),
                txtGrupo.getText(), Integer.parseInt(txtAnno.getText()));
            
             clsCentroFormacion centroFormacion = new clsCentroFormacion();
            ArrayList<Object> centros = centroFormacion.getRegistros();
            String selectedItem = (String) cmbReferencia.getSelectedItem();

            clsModulos Mod1 = new clsModulos();
            ArrayList<Object> modulos = Mod1.getRegistros();
            String selectModulo = (String) cmbModulos.getSelectedItem();

            for (Object centro : centros)
            {
                clsCentroFormacion tempCentro = (clsCentroFormacion) centro;
                                
                if(selectedItem.equals(tempCentro.getCodigo())){
                  System.out.println(selectedItem);
                  m.setReferencia(selectedItem);
                  m.setCentroFormacion(tempCentro);
                }
            }

            //rellenar la lista de modulos disponibles    
            for (Object modulo : modulos)
            {
                clsModulos ModuloTemp = (clsModulos) modulo;
                
                clsModulos m1 = (clsModulos) modulo;
                if(selectModulo.equals(ModuloTemp.getNombre())){
                    System.out.println(ModuloTemp.getNombre());
                    m.setModulos(m1);
                }
                
            }

            if (m.eliminar() == 1)
            {
                JOptionPane.showMessageDialog(null, "El programa a sido eliminado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                this.cargarTabla();
            } else
            {
                JOptionPane.showMessageDialog(null, "No se ha podido eliminar la información", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            CancelarBtn();
        }
    }//GEN-LAST:event_btnElminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnElminar.setEnabled(false);
        txtCodigoPrograma.setEnabled(true);
        txtSector.setEnabled(true);
        cmbReferencia.setEnabled(true);
        cmbModulos.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblProgramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProgramasMouseClicked
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnElminar.setEnabled(true);
        txtCodigoPrograma.setEnabled(false);
        txtSector.setEnabled(false);
        cmbReferencia.setEnabled(false);
        cmbModulos.setEnabled(false);
        

        clsPrograma m = new clsPrograma();
        m = (clsPrograma) m.getRegistro(tblProgramas.getSelectedRow());        
        txtCodigoPrograma.setText(m.getCodigo());
        txtSector.setText(m.getSector());
        txtGrupo.setText(m.getGrupo());
        txtAnno.setText(String.valueOf(m.getAnno()));
    }//GEN-LAST:event_tblProgramasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnElminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbHorario;
    private javax.swing.JComboBox<String> cmbModulos;
    private javax.swing.JComboBox<String> cmbReferencia;
    private javax.swing.JLabel lblAnno;
    private javax.swing.JLabel lblCodigoPrograma;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblSector;
    private javax.swing.JPanel panFormulario;
    private javax.swing.JPanel panModulos;
    private javax.swing.JPanel panOperaciones;
    private javax.swing.JPanel panTabla;
    private javax.swing.JScrollPane scrScroll;
    private javax.swing.JTable tblProgramas;
    private javax.swing.JTextField txtAnno;
    private javax.swing.JTextField txtCodigoPrograma;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtSector;
    // End of variables declaration//GEN-END:variables

    private boolean validar() {
        if (txtSector.getText().length() == 0 || txtSector.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar el sector", "Mensaje", JOptionPane.ERROR_MESSAGE);
            this.formatoError(txtSector);
            return false;
        }

        if (txtCodigoPrograma.getText().length() == 0 || txtCodigoPrograma.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar el codigo del programa", "Mensaje", JOptionPane.ERROR_MESSAGE);
            this.formatoError(txtCodigoPrograma);
            return false;
        }             
       if (txtAnno.getText().length() == 0 || txtAnno.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar un año valido", "Mensaje", JOptionPane.ERROR_MESSAGE);
            this.formatoError(txtAnno);
            return false;
        }
        if (txtGrupo.getText().length() == 0 || txtGrupo.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar el grupo del programa", "Mensaje", JOptionPane.ERROR_MESSAGE);
            this.formatoError(txtGrupo);
            return false;
        }
        try {
            int x = Integer.parseInt(txtAnno.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el año con solo digitos numéricos, ejemplo 2022", "Mensaje", JOptionPane.ERROR_MESSAGE);
            this.formatoError(txtAnno);
            return false;
        }

        return true;
    }

    private void cargarTabla() {
        limpiarCampos();
        clsCentroFormacion centroFormacion = new clsCentroFormacion();
        ArrayList<Object> centros = centroFormacion.getRegistros();
        
        clsPrograma Mod = new clsPrograma();
        ArrayList<Object> programas = Mod.getRegistros();
        
        clsModulos Mod1 = new clsModulos();
        ArrayList<Object> modulos = Mod1.getRegistros();
        
        DefaultTableModel model = (DefaultTableModel) tblProgramas.getModel();
        //borrar filas
        model.setRowCount(0);    
        
        for (Object programa : programas)
        {
           
            clsPrograma m = (clsPrograma) programa;
            
             System.out.println(m.getCodigo());
             
            //generar la fila
            model.addRow(new Object[]
            {
                m.getCodigo(),
                m.getReferencia(),
                m.getModulos(),                
                m.getSector(),
                m.getGrupo(),
                m.getAnno(),                
                m.getCentroFormacion().getNombre()
            });    
        }
        
        //rellenar Centros de formacion:     
        cmbReferencia.removeAllItems();
        for (Object centro : centros)
        {
            clsCentroFormacion tempCentro = (clsCentroFormacion) centro;

            cmbReferencia.addItem(tempCentro.getCodigo());

        }
        


        ArrayList<JCheckBox> checkboxes = new ArrayList<>();
        cmbModulos.removeAllItems();
        //rellenar la lista de modulos disponibles    
        for (Object modulo : modulos)
        {
            clsModulos m1 = (clsModulos) modulo;
            //generar la fila
            cmbModulos.addItem(m1.getNombre());
           
            JCheckBox checkbox = new JCheckBox(m1.getNombre());            
            checkboxes.add(checkbox);
            
        }
        for (JCheckBox checkbox : checkboxes) {
             panModulos.add(checkbox);
           }
    }

    private void CancelarBtn() {
        limpiarCampos();
        txtCodigoPrograma.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnElminar.setEnabled(false);
    }

    private void limpiarCampos() {
        txtCodigoPrograma.setText("");
        txtGrupo.setText("");
        txtAnno.setText("");
        txtSector.setText("");
        txtCodigoPrograma.setEnabled(true);
        txtSector.setEnabled(true);
        cmbReferencia.setEnabled(true);
        cmbModulos.setEnabled(true);
    }

    private void formatoError(Object campo) {
        if (campo instanceof JTextField)
        {
            JTextField txt = (JTextField) campo;
            txt.setForeground(new Color(240, 44, 122));
            txt.setBorder(BorderFactory.createLineBorder(new Color(240, 44, 122)));
            txt.requestFocus();
        }
    }
}
