//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploTecnologiasLegacy.SI.WebService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/EjemploTecnologiasLegacy.Model")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Estado EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Estado Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/EjemploTecnologiasLegacy.Model")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        inactivo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        activo = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioPersona")]
    public interface IServicioPersona {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtenerTodas", ReplyAction="http://tempuri.org/IServicioPersona/ObtenerTodasResponse")]
        EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona[] ObtenerTodas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtenerTodas", ReplyAction="http://tempuri.org/IServicioPersona/ObtenerTodasResponse")]
        System.Threading.Tasks.Task<EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona[]> ObtenerTodasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtenerPorId", ReplyAction="http://tempuri.org/IServicioPersona/ObtenerPorIdResponse")]
        EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona ObtenerPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtenerPorId", ReplyAction="http://tempuri.org/IServicioPersona/ObtenerPorIdResponse")]
        System.Threading.Tasks.Task<EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona> ObtenerPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Agregar", ReplyAction="http://tempuri.org/IServicioPersona/AgregarResponse")]
        void Agregar(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Agregar", ReplyAction="http://tempuri.org/IServicioPersona/AgregarResponse")]
        System.Threading.Tasks.Task AgregarAsync(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Actualizar", ReplyAction="http://tempuri.org/IServicioPersona/ActualizarResponse")]
        void Actualizar(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Actualizar", ReplyAction="http://tempuri.org/IServicioPersona/ActualizarResponse")]
        System.Threading.Tasks.Task ActualizarAsync(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Eliminar", ReplyAction="http://tempuri.org/IServicioPersona/EliminarResponse")]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Eliminar", ReplyAction="http://tempuri.org/IServicioPersona/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Activar", ReplyAction="http://tempuri.org/IServicioPersona/ActivarResponse")]
        void Activar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Activar", ReplyAction="http://tempuri.org/IServicioPersona/ActivarResponse")]
        System.Threading.Tasks.Task ActivarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Desactivar", ReplyAction="http://tempuri.org/IServicioPersona/DesactivarResponse")]
        void Desactivar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Desactivar", ReplyAction="http://tempuri.org/IServicioPersona/DesactivarResponse")]
        System.Threading.Tasks.Task DesactivarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPersonaChannel : EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.IServicioPersona, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPersonaClient : System.ServiceModel.ClientBase<EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.IServicioPersona>, EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.IServicioPersona {
        
        public ServicioPersonaClient() {
        }
        
        public ServicioPersonaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPersonaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona[] ObtenerTodas() {
            return base.Channel.ObtenerTodas();
        }
        
        public System.Threading.Tasks.Task<EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona[]> ObtenerTodasAsync() {
            return base.Channel.ObtenerTodasAsync();
        }
        
        public EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona ObtenerPorId(int id) {
            return base.Channel.ObtenerPorId(id);
        }
        
        public System.Threading.Tasks.Task<EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona> ObtenerPorIdAsync(int id) {
            return base.Channel.ObtenerPorIdAsync(id);
        }
        
        public void Agregar(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona) {
            base.Channel.Agregar(persona);
        }
        
        public System.Threading.Tasks.Task AgregarAsync(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona) {
            return base.Channel.AgregarAsync(persona);
        }
        
        public void Actualizar(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona) {
            base.Channel.Actualizar(persona);
        }
        
        public System.Threading.Tasks.Task ActualizarAsync(EjemploTecnologiasLegacy.SI.WebService.ServiceReference1.Persona persona) {
            return base.Channel.ActualizarAsync(persona);
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public void Activar(int id) {
            base.Channel.Activar(id);
        }
        
        public System.Threading.Tasks.Task ActivarAsync(int id) {
            return base.Channel.ActivarAsync(id);
        }
        
        public void Desactivar(int id) {
            base.Channel.Desactivar(id);
        }
        
        public System.Threading.Tasks.Task DesactivarAsync(int id) {
            return base.Channel.DesactivarAsync(id);
        }
    }
}
