//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.wcf.ServicioPersonaWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/EjemploTecnologiasLegacy.Model")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.wcf.ServicioPersonaWCF.Estado EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaDeNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.wcf.ServicioPersonaWCF.Estado Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeNacimiento {
            get {
                return this.FechaDeNacimientoField;
            }
            set {
                if ((this.FechaDeNacimientoField.Equals(value) != true)) {
                    this.FechaDeNacimientoField = value;
                    this.RaisePropertyChanged("FechaDeNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionField, value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/EjemploTecnologiasLegacy.Model")]
    public enum Estado : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InActivo = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf.ServicioPersonaWCF.IServicioPersona")]
    public interface IServicioPersona {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaLista", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaListaResponse")]
        ConsoleApp1.wcf.ServicioPersonaWCF.Persona[] ObtengaLaLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaLista", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaListaResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona[]> ObtengaLaListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaListaDeActivos", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaListaDeActivosResponse")]
        ConsoleApp1.wcf.ServicioPersonaWCF.Persona[] ObtengaLaListaDeActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaListaDeActivos", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaListaDeActivosResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona[]> ObtengaLaListaDeActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaListaDeInActivos", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaListaDeInActivosResponse")]
        ConsoleApp1.wcf.ServicioPersonaWCF.Persona[] ObtengaLaListaDeInActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaListaDeInActivos", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaListaDeInActivosResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona[]> ObtengaLaListaDeInActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaPersona", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaPersonaResponse")]
        ConsoleApp1.wcf.ServicioPersonaWCF.Persona ObtengaLaPersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/ObtengaLaPersona", ReplyAction="http://tempuri.org/IServicioPersona/ObtengaLaPersonaResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona> ObtengaLaPersonaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Agregue", ReplyAction="http://tempuri.org/IServicioPersona/AgregueResponse")]
        void Agregue(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Agregue", ReplyAction="http://tempuri.org/IServicioPersona/AgregueResponse")]
        System.Threading.Tasks.Task AgregueAsync(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/EditeLaPersona", ReplyAction="http://tempuri.org/IServicioPersona/EditeLaPersonaResponse")]
        void EditeLaPersona(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/EditeLaPersona", ReplyAction="http://tempuri.org/IServicioPersona/EditeLaPersonaResponse")]
        System.Threading.Tasks.Task EditeLaPersonaAsync(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Active", ReplyAction="http://tempuri.org/IServicioPersona/ActiveResponse")]
        void Active(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/Active", ReplyAction="http://tempuri.org/IServicioPersona/ActiveResponse")]
        System.Threading.Tasks.Task ActiveAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/DesActive", ReplyAction="http://tempuri.org/IServicioPersona/DesActiveResponse")]
        void DesActive(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPersona/DesActive", ReplyAction="http://tempuri.org/IServicioPersona/DesActiveResponse")]
        System.Threading.Tasks.Task DesActiveAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPersonaChannel : ConsoleApp1.wcf.ServicioPersonaWCF.IServicioPersona, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPersonaClient : System.ServiceModel.ClientBase<ConsoleApp1.wcf.ServicioPersonaWCF.IServicioPersona>, ConsoleApp1.wcf.ServicioPersonaWCF.IServicioPersona {
        
        public ServicioPersonaClient() {
        }
        
        public ServicioPersonaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPersonaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPersonaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApp1.wcf.ServicioPersonaWCF.Persona[] ObtengaLaLista() {
            return base.Channel.ObtengaLaLista();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona[]> ObtengaLaListaAsync() {
            return base.Channel.ObtengaLaListaAsync();
        }
        
        public ConsoleApp1.wcf.ServicioPersonaWCF.Persona[] ObtengaLaListaDeActivos() {
            return base.Channel.ObtengaLaListaDeActivos();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona[]> ObtengaLaListaDeActivosAsync() {
            return base.Channel.ObtengaLaListaDeActivosAsync();
        }
        
        public ConsoleApp1.wcf.ServicioPersonaWCF.Persona[] ObtengaLaListaDeInActivos() {
            return base.Channel.ObtengaLaListaDeInActivos();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona[]> ObtengaLaListaDeInActivosAsync() {
            return base.Channel.ObtengaLaListaDeInActivosAsync();
        }
        
        public ConsoleApp1.wcf.ServicioPersonaWCF.Persona ObtengaLaPersona(int id) {
            return base.Channel.ObtengaLaPersona(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.wcf.ServicioPersonaWCF.Persona> ObtengaLaPersonaAsync(int id) {
            return base.Channel.ObtengaLaPersonaAsync(id);
        }
        
        public void Agregue(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona) {
            base.Channel.Agregue(persona);
        }
        
        public System.Threading.Tasks.Task AgregueAsync(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona) {
            return base.Channel.AgregueAsync(persona);
        }
        
        public void EditeLaPersona(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona) {
            base.Channel.EditeLaPersona(persona);
        }
        
        public System.Threading.Tasks.Task EditeLaPersonaAsync(ConsoleApp1.wcf.ServicioPersonaWCF.Persona persona) {
            return base.Channel.EditeLaPersonaAsync(persona);
        }
        
        public void Active(int id) {
            base.Channel.Active(id);
        }
        
        public System.Threading.Tasks.Task ActiveAsync(int id) {
            return base.Channel.ActiveAsync(id);
        }
        
        public void DesActive(int id) {
            base.Channel.DesActive(id);
        }
        
        public System.Threading.Tasks.Task DesActiveAsync(int id) {
            return base.Channel.DesActiveAsync(id);
        }
    }
}
