//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1TecnologiasLegacy.UIWPF.ServiceWCFVehiculo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWCFVehiculo.IServiceWCFVehiculo")]
    public interface IServiceWCFVehiculo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/ObtenerTodas", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/ObtenerTodasResponse")]
        Laboratorio1TecnologiasLegacy.Model.Vehiculo[] ObtenerTodas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/ObtenerTodas", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/ObtenerTodasResponse")]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.Model.Vehiculo[]> ObtenerTodasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/ObtenerPorId", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/ObtenerPorIdResponse")]
        Laboratorio1TecnologiasLegacy.Model.Vehiculo ObtenerPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/ObtenerPorId", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/ObtenerPorIdResponse")]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.Model.Vehiculo> ObtenerPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/Agregar", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/AgregarResponse")]
        void Agregar(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/Agregar", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/AgregarResponse")]
        System.Threading.Tasks.Task AgregarAsync(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/Actualizar", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/ActualizarResponse")]
        void Actualizar(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/Actualizar", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/ActualizarResponse")]
        System.Threading.Tasks.Task ActualizarAsync(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/Eliminar", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/EliminarResponse")]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCFVehiculo/Eliminar", ReplyAction="http://tempuri.org/IServiceWCFVehiculo/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCFVehiculoChannel : Laboratorio1TecnologiasLegacy.UIWPF.ServiceWCFVehiculo.IServiceWCFVehiculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCFVehiculoClient : System.ServiceModel.ClientBase<Laboratorio1TecnologiasLegacy.UIWPF.ServiceWCFVehiculo.IServiceWCFVehiculo>, Laboratorio1TecnologiasLegacy.UIWPF.ServiceWCFVehiculo.IServiceWCFVehiculo {
        
        public ServiceWCFVehiculoClient() {
        }
        
        public ServiceWCFVehiculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCFVehiculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFVehiculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFVehiculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Laboratorio1TecnologiasLegacy.Model.Vehiculo[] ObtenerTodas() {
            return base.Channel.ObtenerTodas();
        }
        
        public System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.Model.Vehiculo[]> ObtenerTodasAsync() {
            return base.Channel.ObtenerTodasAsync();
        }
        
        public Laboratorio1TecnologiasLegacy.Model.Vehiculo ObtenerPorId(int id) {
            return base.Channel.ObtenerPorId(id);
        }
        
        public System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.Model.Vehiculo> ObtenerPorIdAsync(int id) {
            return base.Channel.ObtenerPorIdAsync(id);
        }
        
        public void Agregar(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo) {
            base.Channel.Agregar(vehiculo);
        }
        
        public System.Threading.Tasks.Task AgregarAsync(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo) {
            return base.Channel.AgregarAsync(vehiculo);
        }
        
        public void Actualizar(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo) {
            base.Channel.Actualizar(vehiculo);
        }
        
        public System.Threading.Tasks.Task ActualizarAsync(Laboratorio1TecnologiasLegacy.Model.Vehiculo vehiculo) {
            return base.Channel.ActualizarAsync(vehiculo);
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
    }
}
