# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\lsuazo\OneDrive - DXC Production\Documents\New folder\EntregaLaboratoriosProgaII\Laboratorio#7\MiguelFernandezArteaga\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(605, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.BtnCrear = QtWidgets.QPushButton(Dialog)
        self.BtnCrear.setGeometry(QtCore.QRect(20, 240, 121, 23))
        self.BtnCrear.setObjectName("BtnCrear")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(320, 10, 258, 213))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.TxtLeer = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.TxtLeer.setObjectName("TxtLeer")
        self.verticalLayout_2.addWidget(self.TxtLeer)
        self.BtnLeer = QtWidgets.QPushButton(Dialog)
        self.BtnLeer.setGeometry(QtCore.QRect(320, 240, 75, 23))
        self.BtnLeer.setObjectName("BtnLeer")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 10, 258, 213))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.TxtEscribir = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        self.TxtEscribir.setObjectName("TxtEscribir")
        self.verticalLayout.addWidget(self.TxtEscribir)
        self.BtnLeerXLinea = QtWidgets.QPushButton(Dialog)
        self.BtnLeerXLinea.setGeometry(QtCore.QRect(420, 240, 91, 23))
        self.BtnLeerXLinea.setObjectName("BtnLeerXLinea")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.BtnCrear, self.TxtEscribir)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Gestor de archivos MyPime"))
        self.BtnCrear.setText(_translate("Dialog", "Escribir en archivo"))
        self.label_2.setText(_translate("Dialog", "Leer"))
        self.BtnLeer.setText(_translate("Dialog", "LeerArchivo"))
        self.label.setText(_translate("Dialog", "Escribir"))
        self.BtnLeerXLinea.setText(_translate("Dialog", "LeerXLinea"))
