//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehiculo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Vehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Marca MarcaField;
        
        private int AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        private bool DobleTraccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Marca Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((this.MarcaField.Equals(value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool DobleTraccion {
            get {
                return this.DobleTraccionField;
            }
            set {
                if ((this.DobleTraccionField.Equals(value) != true)) {
                    this.DobleTraccionField = value;
                    this.RaisePropertyChanged("DobleTraccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://tempuri.org/")]
    public enum Marca : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tesla = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Toyota = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BYD = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioVehiculoWebService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name ObtenerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener", ReplyAction="*")]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponse Obtener(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponse> ObtenerAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest request);
        
        // CODEGEN: Generating message contract since element name vehiculo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponse Actualizar(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponse> ActualizarAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest request);
        
        // CODEGEN: Generating message contract since element name vehiculo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponse Agregar(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponse> AgregarAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task EliminarAsync(int id);
        
        // CODEGEN: Generating message contract since element name ObtenerPorIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPorId", ReplyAction="*")]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponse ObtenerPorId(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponse> ObtenerPorIdAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtener", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequestBody Body;
        
        public ObtenerRequest() {
        }
        
        public ObtenerRequest(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerRequestBody {
        
        public ObtenerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponseBody Body;
        
        public ObtenerResponse() {
        }
        
        public ObtenerResponse(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo[] ObtenerResult;
        
        public ObtenerResponseBody() {
        }
        
        public ObtenerResponseBody(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo[] ObtenerResult) {
            this.ObtenerResult = ObtenerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Actualizar", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequestBody Body;
        
        public ActualizarRequest() {
        }
        
        public ActualizarRequest(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo;
        
        public ActualizarRequestBody() {
        }
        
        public ActualizarRequestBody(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo) {
            this.vehiculo = vehiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponseBody Body;
        
        public ActualizarResponse() {
        }
        
        public ActualizarResponse(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActualizarResponseBody {
        
        public ActualizarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Agregar", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequestBody Body;
        
        public AgregarRequest() {
        }
        
        public AgregarRequest(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo;
        
        public AgregarRequestBody() {
        }
        
        public AgregarRequestBody(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo) {
            this.vehiculo = vehiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponseBody Body;
        
        public AgregarResponse() {
        }
        
        public AgregarResponse(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AgregarResponseBody {
        
        public AgregarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPorId", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequestBody Body;
        
        public ObtenerPorIdRequest() {
        }
        
        public ObtenerPorIdRequest(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ObtenerPorIdRequestBody() {
        }
        
        public ObtenerPorIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponseBody Body;
        
        public ObtenerPorIdResponse() {
        }
        
        public ObtenerPorIdResponse(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo ObtenerPorIdResult;
        
        public ObtenerPorIdResponseBody() {
        }
        
        public ObtenerPorIdResponseBody(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo ObtenerPorIdResult) {
            this.ObtenerPorIdResult = ObtenerPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap>, Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponse Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.Obtener(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest request) {
            return base.Channel.Obtener(request);
        }
        
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo[] Obtener() {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequestBody();
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponse retVal = ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).Obtener(inValue);
            return retVal.Body.ObtenerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponse> Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.ObtenerAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest request) {
            return base.Channel.ObtenerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerResponse> ObtenerAsync() {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerRequestBody();
            return ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).ObtenerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponse Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.Actualizar(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest request) {
            return base.Channel.Actualizar(request);
        }
        
        public void Actualizar(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo) {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequestBody();
            inValue.Body.vehiculo = vehiculo;
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponse retVal = ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).Actualizar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponse> Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.ActualizarAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest request) {
            return base.Channel.ActualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarResponse> ActualizarAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo) {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ActualizarRequestBody();
            inValue.Body.vehiculo = vehiculo;
            return ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).ActualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponse Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.Agregar(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest request) {
            return base.Channel.Agregar(request);
        }
        
        public void Agregar(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo) {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequestBody();
            inValue.Body.vehiculo = vehiculo;
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponse retVal = ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).Agregar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponse> Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.AgregarAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest request) {
            return base.Channel.AgregarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarResponse> AgregarAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo vehiculo) {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.AgregarRequestBody();
            inValue.Body.vehiculo = vehiculo;
            return ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).AgregarAsync(inValue);
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponse Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.ObtenerPorId(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest request) {
            return base.Channel.ObtenerPorId(request);
        }
        
        public Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.Vehiculo ObtenerPorId(int id) {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequestBody();
            inValue.Body.id = id;
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponse retVal = ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).ObtenerPorId(inValue);
            return retVal.Body.ObtenerPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponse> Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap.ObtenerPorIdAsync(Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest request) {
            return base.Channel.ObtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdResponse> ObtenerPorIdAsync(int id) {
            Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest inValue = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequest();
            inValue.Body = new Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.ObtenerPorIdRequestBody();
            inValue.Body.id = id;
            return ((Laboratorio1TecnologiasLegacy.UIConsole.ServicioVehiculoWebService.WebService1Soap)(this)).ObtenerPorIdAsync(inValue);
        }
    }
}
